# Generated by Django 5.1.4 on 2026-06-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded (fallback active)'), ('crashed', 'Crashed'), ('restarted', 'Restarted')], default='healthy', max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('fallback_used', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FusedTrustRiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=128)),
                ('score', models.FloatField()),
                ('modules', models.JSONField(default=list)),
                ('signals', models.JSONField(default=list)),
                ('ts', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('signal', models.CharField(max_length=64)),
                ('identifier', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('route', models.CharField(default='cloud', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='EvidencePacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('body', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending human approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=24)),
                ('approved_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fused_risk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='core.fusedtrustriskrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
