# Generated by Django 5.1.4 on 2026-07-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('category', models.CharField(choices=[('digital_arrest', 'Digital arrest / fake officer'), ('kyc_otp', 'KYC / OTP / bank fraud'), ('courier', 'Courier / parcel seizure'), ('upi_refund', 'UPI / refund / remote access'), ('investment', 'Investment / job / lottery scam'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reporter_contact', models.CharField(blank=True, default='', max_length=128)),
                ('channel', models.CharField(blank=True, default='web', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
