# Generated by Django 5.1.4 on 2026-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fraudreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=24)),
                ('identifier', models.CharField(db_index=True, max_length=256)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('kind', 'identifier')},
            },
        ),
    ]
